ALTER TABLE homestays
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE homestays
ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;

ALTER TABLE homestays
ADD COLUMN IF NOT EXISTS inquiry_count BIGINT NOT NULL DEFAULT 0;
