ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS post_type VARCHAR(32),
    ADD COLUMN IF NOT EXISTS is_editorial BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_trending BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS editorial_score DOUBLE PRECISION NOT NULL DEFAULT 0;

