package com.nbh.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.nbh.backend.model.PostType;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Lightweight projection DTO for community feed.
 * Designed to avoid Hibernate lazy-loading traps by using SQL aggregation
 * and batch queries instead of entity collection access.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PostFeedDto {

    private UUID postId;
    private String textContent;
    private Instant createdAt;
    
    // Author (pre-loaded via JOIN)
    private UUID authorId;
    private String authorName;
    private String authorAvatarUrl;
    private String authorRole;
    private boolean authorVerifiedHost;
    private boolean isLikedByCurrentUser;
    
    // Counts (pre-computed via SQL aggregation)
    private int commentCount;
    private int likeCount;
    private int shareCount;
    
    // Optional homestay reference
    private UUID homestayId;
    private String homestayName;
    private UUID destinationId;
    private PostType postType;
    private boolean isEditorial;
    private boolean isFeatured;
    private boolean isPinned;
    private boolean isTrending;
    private int viewCount;
    private double trendingScore;
    private double editorialScore;
    
    // Tags (loaded via batch query)
    private List<String> tags;
    
    // Media variants (loaded via batch query with ImageKit transforms)
    private List<MediaVariantDto> media;
    
    // Repost metadata (minimal, no recursion)
    private boolean isRepost;
    private UUID originalPostId;
    private String originalAuthorName;
    private String originalContentPreview; // First 150 chars
    
    // Layout metadata for FeedLayoutEngine
    private Integer mediaCount;      // Number of media attachments
    private Integer textLength;      // Character count of textContent
    private List<ImageDimDto> imageDimensions;  // Image width/height for aspect ratio
    private String postCategory;     // Editorial category (nullable)
    private Integer postPriority;    // Editorial priority score (nullable)
    
    // ========================================================================
    // Elevation Engine Fields (V58 Migration)
    // ========================================================================
    private Integer helpfulCount;    // Number of helpful votes on this post
    private Integer lastComputedXp;  // Last computed XP for this post
    
    /**
     * Image dimensions for layout decisions.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ImageDimDto {
        private UUID mediaId;
        private Integer width;
        private Integer height;
        private Double aspectRatio;  // width/height, computed if both present
    }
    
    /**
     * Author information for feed display.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AuthorDto {
        private UUID id;
        private String name;
        private String avatarUrl;
        private String role;
        private boolean isVerifiedHost;
    }

    /**
     * Media variant with multiple resolution URLs for responsive images.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MediaVariantDto {
        private UUID id;
        private String fileId;
        private String originalUrl;
        private String thumbnail;  // w-200,q-60,f-auto
        private String small;      // w-480,q-70,f-auto
        private String medium;     // w-800,q-75,f-auto
        private String large;      // w-1200,q-80,f-auto
    }
    
    /**
     * Cursor for pagination (encoded as Base64 JSON by controller).
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Cursor {
        private Instant createdAt;
        private UUID id;
        private Double trendingScore;
        private String previousBlockType;
        private Integer previousBlockTypeRun;
    }
    
    /**
     * Cursor-paginated response wrapper.
     * Includes optional blocks for backend-driven layout.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FeedResponse {
        private List<PostFeedDto> posts;
        private String nextCursor;
        private boolean hasMore;
        // Optional layout blocks (when layout=true)
        private List<FeedBlockDto> blocks;
    }
    
    /**
     * Feed block for editorial layout.
     * Generated by FeedLayoutEngine when layout=true.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FeedBlockDto {
        private String blockId;           // Unique block identifier
        private BlockType blockType;      // FEATURED, STANDARD, COLLAGE, PHOTO, HERO, PLACEHOLDER
        private int blockPosition;         // Position in feed (0-indexed)
        private int blockPriority;        // Priority score used for assignment
        private List<UUID> postIds;       // Posts in this block (usually 1, can be 2+ for collage)
        private RenderHints renderHints;  // Rendering hints for frontend
        
        public enum BlockType {
            FEATURED,      // Large hero-style card (16:9 aspect ratio)
            STANDARD,      // Default card size (4:5 aspect ratio)
            COLLAGE,       // Multi-image grid (4:5 container with grid layout)
            PHOTO,         // Image-focused with minimal text (4:5 aspect ratio)
            HERO,          // Full-width hero block (16:9 aspect ratio)
            PLACEHOLDER    // "Be the first to post" prompt (16:9 aspect ratio)
        }
        
        @Data
        @Builder
        @NoArgsConstructor
        @AllArgsConstructor
        public static class RenderHints {
            private String aspectRatio;     // "16/9", "4/5", "1/1", etc.
            private Integer maxImageHeight; // Max height in px
            private Boolean showExcerpt;    // Show text excerpt
            private String layoutMode;      // "single", "grid-2", "grid-3"
        }
    }
}
