/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This file is maintained locally to match the canonical homestay detail/add-listing contract.
 */

export interface HomestayMedia {
    'id'?: string;
    'url'?: string;
    'fileId'?: string;
}

export interface HomestaySpaceMedia {
    'url'?: string;
    'fileId'?: string;
    'caption'?: string;
}

export interface HomestaySpace {
    'type'?: 'room' | 'bathroom' | 'common' | 'outdoor';
    'name'?: string;
    'description'?: string;
    'media'?: Array<HomestaySpaceMedia>;
}

export interface HomestayVideo {
    'url'?: string;
    'title'?: string;
    'type'?: 'property' | 'room' | 'experience';
}

export interface HomestayAttraction {
    'name'?: string;
    'distance'?: string;
    'time'?: string;
    'type'?: 'nature' | 'culture' | 'cafe';
    'highlight'?: boolean;
}

export interface HomestayOffer {
    'type'?: 'DEAL' | 'SEASONAL' | 'LAST_MINUTE';
    'title'?: string;
    'description'?: string;
    'validity'?: string;
    'tags'?: Array<string>;
}

export interface HomestayStructuredPolicies {
    'checkIn'?: string;
    'checkOut'?: string;
    'paymentType'?: Array<string>;
    'petsAllowed'?: boolean;
    'alcoholAllowed'?: string;
}

export interface HomestayHost {
    'id'?: string;
    'name'?: string;
    'role'?: string;
    'avatarUrl'?: string;
    'isVerifiedHost'?: boolean;
}

export interface HomestayDestination {
    'id'?: string;
    'name'?: string;
    'slug'?: string;
    'district'?: string;
    'stateName'?: string;
    'stateSlug'?: string;
}

export interface Homestay {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'pricePerNight'?: number;
    'latitude'?: number;
    'longitude'?: number;
    'locationName'?: string;
    'amenities'?: { [key: string]: boolean; };
    'policies'?: Array<string>;
    'quickFacts'?: { [key: string]: string; };
    'tags'?: Array<string>;
    'hostDetails'?: { [key: string]: any; };
    'media'?: Array<HomestayMedia>;
    'vibeScore'?: number;
    'avgAtmosphereRating'?: number;
    'avgServiceRating'?: number;
    'avgAccuracyRating'?: number;
    'avgValueRating'?: number;
    'totalReviews'?: number;
    'host'?: HomestayHost;
    'status'?: HomestayStatusEnum;
    'ownerId'?: string;
    'featured'?: boolean;
    'destination'?: HomestayDestination;
    'mealConfig'?: { [key: string]: any; };
    'spaces'?: Array<HomestaySpace>;
    'videos'?: Array<HomestayVideo>;
    'attractions'?: Array<HomestayAttraction>;
    'offers'?: HomestayOffer;
    'structuredPolicies'?: HomestayStructuredPolicies;
    'mealPlanCode'?: string;
    'mealPlanLabel'?: string;
    'editorialLead'?: string;
    'nearbyHighlights'?: Array<string>;
    'bookingHeatScore'?: number;
    'trustSignals'?: Array<string>;
}

export const HomestayStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;

export type HomestayStatusEnum = typeof HomestayStatusEnum[keyof typeof HomestayStatusEnum];
