/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

export interface Homestay {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'owner'?: User;
    'pricePerNight'?: number;
    'latitude'?: number;
    'longitude'?: number;
    'address'?: string;
    'amenities'?: { [key: string]: boolean; };
    'photoUrls'?: Array<string>;
    'vibeScore'?: number;
    'status'?: HomestayStatusEnum;
}

export const HomestayStatusEnum = {
    Pending: 'PENDING',
    Approved: 'APPROVED',
    Rejected: 'REJECTED'
} as const;

export type HomestayStatusEnum = typeof HomestayStatusEnum[keyof typeof HomestayStatusEnum];


