/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RegisterRequest {
    'firstname'?: string;
    'lastname'?: string;
    'email'?: string;
    'password'?: string;
    'role'?: RegisterRequestRoleEnum;
}

export const RegisterRequestRoleEnum = {
    RoleUser: 'ROLE_USER',
    RoleHost: 'ROLE_HOST',
    RoleAdmin: 'ROLE_ADMIN'
} as const;

export type RegisterRequestRoleEnum = typeof RegisterRequestRoleEnum[keyof typeof RegisterRequestRoleEnum];


