/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Response {
    'id'?: string;
    'userId'?: string;
    'userName'?: string;
    'locationName'?: string;
    'textContent'?: string;
    'imageUrls'?: Array<string>;
    'createdAt'?: string;
}

