/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GrantedAuthority } from './granted-authority';

export interface User {
    'id'?: string;
    'email'?: string;
    'password'?: string;
    'role'?: UserRoleEnum;
    'enabled'?: boolean;
    'firstName'?: string;
    'lastName'?: string;
    'accountNonLocked'?: boolean;
    'username'?: string;
    'credentialsNonExpired'?: boolean;
    'accountNonExpired'?: boolean;
    'authorities'?: Array<GrantedAuthority>;
}

export const UserRoleEnum = {
    RoleUser: 'ROLE_USER',
    RoleHost: 'ROLE_HOST',
    RoleAdmin: 'ROLE_ADMIN'
} as const;

export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


