spring:
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 2000
      idle-timeout: 30000
      max-lifetime: 1800000
  flyway:
    out-of-order: false
    baseline-on-migrate: true
    connect-retries: 5
    enabled: true
